### ISSUE TITLE
Fine tune blog creation

### ISSUE THREAD

**Issue by hansquiogue** [DACSS/blogbuilder#9]
- ~~Make prompts slower and appear in order~~
- ~~Allow ability to disable interactivity~~

**Comment by hansquiogue** [comment]
TODO: 
- Account for .git repo links

**Comment by naman159** [comment]
> TODO:
> 
> * Account for .git repo links

We can make the process opinionated such that the links we input are without '.git' in the end. For example, https://github.com/DACSS/blogbuilder instead of https://github.com/DACSS/blogbuilder.git should be put for repo link.

I tested this and it is working properly.
